### ISSUE TITLE
Create Table Script Uses DECIMAL instead of NUMBER for Datatypes that are NUMBER

### ISSUE THREAD

**Issue by jreed-cartago** [squirrel-sql-client/squirrel-sql-code#1]
So I created a SQL Create Table Script to get the structure of a table into the editor, the table is so structured 

![image](https://user-images.githubusercontent.com/72963764/182781095-b5f00cd4-10ef-4c0e-9156-0b86708cdedf.png)

but the SQL generation looks like this

![image](https://user-images.githubusercontent.com/72963764/182781480-61286f36-8dcc-432b-bb85-7f85f911dc3a.png)

**Comment by gerdwagner** [comment]
Could you please give some details on you database and JDBC driver. Product name and version of both would help to reproduce your problem.

**Comment by jreed-cartago** [comment]
Hello yes. The database to which I am connecting is an Oracle 18c Express. I'm currently using the the oracle.jdbc.OracleDriver version 6 from what I can tell, using the ojdbc6.jar file. This would be using the Oracle Thin Driver.

**Comment by gerdwagner** [comment]
Fixed in our GIT repositories. Will be available in future snapshots ans versions.

Excerpt from change log:
https://github.com/squirrel-sql-client/squirrel-sql-code/issues/1
  Table scripts for Oracle RDBMS:
  For Oracle databases right mouse click on table in Object tree --> Scripts --> Create Table Script
  scripted columns of type number as decimal.
